export const clerkAuthAppearance = {
  variables: {
    colorPrimary: "#047857",
    colorText: "#0f172a",
    colorTextSecondary: "#64748b",
    colorBackground: "#ffffff",
    colorInputBackground: "#ffffff",
    colorInputText: "#0f172a",
    borderRadius: "0.75rem",
    fontFamily: "Arial, Helvetica, sans-serif",
  },
  elements: {
    rootBox: "w-full",
    card: "w-full border-0 bg-transparent p-0 shadow-none",
    header: "hidden",
    socialButtonsBlockButton: "min-h-11 border-slate-200 text-slate-700 shadow-none hover:bg-slate-50",
    socialButtonsBlockButtonText: "font-semibold",
    dividerLine: "bg-slate-200",
    dividerText: "text-slate-400",
    formFieldLabel: "text-sm font-semibold text-slate-700",
    formFieldInput: "min-h-11 border-slate-300 text-slate-950 shadow-none focus:border-emerald-700 focus:ring-emerald-700",
    formButtonPrimary: "min-h-11 bg-emerald-800 text-sm font-semibold shadow-sm hover:bg-emerald-900",
    footer: "mt-5",
    footerActionText: "text-slate-500",
    footerActionLink: "font-semibold text-emerald-800 hover:text-emerald-900",
    identityPreviewText: "text-slate-700",
    formResendCodeLink: "text-emerald-800",
  },
};
